---
# Semantic Release Configuration

branches:
  - name: main
    channel: stable
  - name: develop
    channel: beta
    prerelease: true

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: refactor
          release: patch
        - type: docs
          release: false
        - type: chore
          release: false
        - type: test
          release: false
        - type: ci
          release: false
        - breaking: true
          release: major

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: Features
            hidden: false
          - type: fix
            section: Bug Fixes
            hidden: false
          - type: perf
            section: Performance Improvements
            hidden: false
          - type: refactor
            section: Code Refactoring
            hidden: false
          - type: chore
            section: Maintenance
            hidden: false
          - type: docs
            section: Documentation
            hidden: false
          - type: test
            section: Tests
            hidden: false
          - type: ci
            section: CI/CD
            hidden: false

  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: |
        # Changelog

        All notable changes to this project will be documented in this file.

        The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
        and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

  # Update VERSION file and meta/main.yml with new version
  - - "@semantic-release/exec"
    - prepareCmd: |
        echo ${nextRelease.version} > VERSION
        sed -i.bak "s/^\(  version:\).*/\1 ${nextRelease.version}/" meta/main.yml && rm -f meta/main.yml.bak

  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - VERSION
        - meta/main.yml
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  - - "@semantic-release/github"
    - assets:
        - path: CHANGELOG.md
          label: Changelog

tagFormat: v${version}
ci: true
dryRun: false
