---
# Molecule verification playbook - validates ISO manager role results

- name: Verify
  hosts: all
  gather_facts: true

  tasks:
    # =========================================================================
    # 1. Directory Existence Verification
    # =========================================================================

    - name: Check ISO storage directory exists
      ansible.builtin.stat:
        path: /var/lib/isos
      register: iso_dir

    - name: Verify ISO storage directory
      ansible.builtin.assert:
        that:
          - iso_dir.stat.exists
          - iso_dir.stat.isdir
        fail_msg: "ISO storage directory /var/lib/isos does not exist"

    - name: Check mount root directory exists
      ansible.builtin.stat:
        path: /var/lib/iso_mounts
      register: mount_dir

    - name: Verify mount root directory
      ansible.builtin.assert:
        that:
          - mount_dir.stat.exists
          - mount_dir.stat.isdir
        fail_msg: "Mount root directory /var/lib/iso_mounts does not exist"

    # =========================================================================
    # 2. ISO File Verification
    # =========================================================================

    - name: Check tinycore ISO file exists
      ansible.builtin.stat:
        path: /var/lib/isos/tinycore-17.0.iso
      register: iso_file

    - name: Verify tinycore ISO file exists
      ansible.builtin.assert:
        that:
          - iso_file.stat.exists
          - iso_file.stat.isreg
        fail_msg: "TinyCore ISO file does not exist"

    # =========================================================================
    # 3. Mount Point Verification
    # =========================================================================

    - name: Check mount point directory exists
      ansible.builtin.stat:
        path: /var/lib/iso_mounts/tinycore-17.0
      register: mount_point

    - name: Verify mount point directory exists
      ansible.builtin.assert:
        that:
          - mount_point.stat.exists
          - mount_point.stat.isdir
        fail_msg: "Mount point /var/lib/iso_mounts/tinycore-17.0 does not exist"

    # Commented out due to containerization and loop device mounting. Likely to work under rootful docker.
    # - name: Check ISO is actually mounted
    #   ansible.builtin.command:
    #     cmd: findmnt -n /var/lib/iso_mounts/tinycore-17.0
    #   register: mount_check
    #   changed_when: false
    #   failed_when: false

    # - name: Verify ISO is mounted
    #   ansible.builtin.assert:
    #     that:
    #       - mount_check.rc == 0
    #     fail_msg: "ISO is not mounted at /var/lib/iso_mounts/tinycore-17.0"

    # # =========================================================================
    # # 4. Mounted Content Verification
    # # =========================================================================

    # - name: Check boot directory is accessible via mount
    #   ansible.builtin.stat:
    #     path: /var/lib/iso_mounts/tinycore-17.0/boot
    #   register: boot_dir

    # - name: Verify boot directory accessible
    #   ansible.builtin.assert:
    #     that:
    #       - boot_dir.stat.exists
    #       - boot_dir.stat.isdir
    #     fail_msg: "Boot directory not accessible at mount point"

    # =========================================================================
    # 5. Directory Permission Verification
    # =========================================================================

    - name: Check ISO storage directory permissions
      ansible.builtin.stat:
        path: /var/lib/isos
      register: iso_dir_perms

    - name: Verify ISO storage directory permissions
      ansible.builtin.assert:
        that:
          - iso_dir_perms.stat.mode == "0755"
        fail_msg: "ISO storage directory has incorrect permissions: {{ iso_dir_perms.stat.mode }}"

    - name: Display verification summary
      ansible.builtin.debug:
        msg: |
          ✓ All verification checks passed!
          - Directories: /var/lib/isos and /var/lib/iso_mounts exist
          - ISO file: tinycore-17.0.iso present
          - Permissions: correct (0755)
