---
# Molecule verification playbook - validates ISO manager role results

- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # =========================================================================
    # 1. Directory Existence Verification
    # =========================================================================

    - name: Check ISO storage directory exists
      ansible.builtin.stat:
        path: /var/lib/isos
      register: iso_dir

    - name: Verify ISO storage directory
      ansible.builtin.assert:
        that:
          - iso_dir.stat.exists
          - iso_dir.stat.isdir
        fail_msg: "ISO storage directory /var/lib/isos does not exist"

    - name: Check mount root directory exists
      ansible.builtin.stat:
        path: /var/lib/iso_mounts
      register: mount_dir

    - name: Verify mount root directory
      ansible.builtin.assert:
        that:
          - mount_dir.stat.exists
          - mount_dir.stat.isdir
        fail_msg: "Mount root directory /var/lib/iso_mounts does not exist"

    # =========================================================================
    # 2. ISO File Verification
    # =========================================================================

    - name: Check alpine ISO file exists
      ansible.builtin.stat:
        path: /var/lib/isos/alpine-3.23.iso
      register: iso_file

    - name: Verify alpine ISO file exists
      ansible.builtin.assert:
        that:
          - iso_file.stat.exists
          - iso_file.stat.isreg
        fail_msg: "Alpine ISO file does not exist"

    # =========================================================================
    # 3. Mount Point Verification
    # =========================================================================

    - name: Check mount point directory exists
      ansible.builtin.stat:
        path: /var/lib/iso_mounts/alpine-3.23
      register: mount_point

    - name: Verify mount point directory exists
      ansible.builtin.assert:
        that:
          - mount_point.stat.exists
          - mount_point.stat.isdir
        fail_msg: "Mount point /var/lib/iso_mounts/alpine-3.23 does not exist"

    - name: Check ISO is actually mounted
      ansible.builtin.command:
        cmd: findmnt -n /var/lib/iso_mounts/alpine-3.23
      register: mount_check
      changed_when: false
      failed_when: false

    - name: Verify ISO is mounted
      ansible.builtin.assert:
        that:
          - mount_check.rc == 0
        fail_msg: "ISO is not mounted at /var/lib/iso_mounts/alpine-3.23"

    # =========================================================================
    # 4. Mounted Content Verification
    # =========================================================================

    - name: Check boot directory is accessible via mount
      ansible.builtin.stat:
        path: /var/lib/iso_mounts/alpine-3.23/boot
      register: boot_dir

    - name: Verify boot directory accessible
      ansible.builtin.assert:
        that:
          - boot_dir.stat.exists
          - boot_dir.stat.isdir
        fail_msg: "Boot directory not accessible at mount point"

    # =========================================================================
    # 5. Directory Permission Verification
    # =========================================================================

    - name: Check ISO storage directory permissions
      ansible.builtin.stat:
        path: /var/lib/isos
      register: iso_dir_perms

    - name: Verify ISO storage directory permissions
      ansible.builtin.assert:
        that:
          - iso_dir_perms.stat.mode == "0755"
        fail_msg: "ISO storage directory has incorrect permissions: {{ iso_dir_perms.stat.mode }}"

    - name: Display verification summary
      ansible.builtin.debug:
        msg: |
          ✓ All verification checks passed!
          - Directories: /var/lib/isos and /var/lib/iso_mounts exist
          - ISO file: alpine-3.23.iso present
          - Mount: alpine-3.23 mounted and accessible
          - Boot directory: accessible via mount point
          - Permissions: correct (0755)
